### ISSUE TITLE
Name collision with the wallShearStress object

### ISSUE THREAD

**Issue by timofeymukha** [timofeymukha/libWallModelledLES#3]
Both the library and the FO will try to use the same field name, which causes collision.

@shor-ty

**Comment by timofeymukha** [comment]
Suggest improvements to the FO: possibility to select a name

**Comment by timofeymukha** [comment]
See https://develop.openfoam.com/Development/openfoam/-/issues/2767 for a workaround!

**Comment by LUOFQ5** [comment]
Inconsistent results for wallShearStress. I have used the functionObjects wallShearStress with "useNamePrefix". It actually outputs two wallShearStress fields, but they seem to be inconsistent.    The test case is periodic-hill.

**Comment by timofeymukha** [comment]
@LUOFQ5 Two fields are to be expected. One field comes from libWallModelledLES, and the other one from the FO (it should have the prefix). So, there really is no need to use the FO, since the library will give you the stress field itself.

The library does compute the stress somewhat differently from the FO. I think differences will only show up in a curved-boundary case like yours. I need to look more into this. I will open a separate issue. How large is the inconsistency in your case?

**Comment by LUOFQ5** [comment]
@timofeymukha   Sorry for the incomplete and inaccurate information. I made a mistake in postprocessing. In fact, the WSS fields from the FO and libWallModelledLES are essentially identical. Specifically, when using the LOWT model, the two WSS are exactly the same (differ by a negative sign). And when using the ODE type, there may be small differences. I do not believe this to be a problem.
![image](https://github.com/timofeymukha/libWallModelledLES/assets/62541370/940616a3-2a52-46ab-8dca-c8448e41af57)
![image](https://github.com/timofeymukha/libWallModelledLES/assets/62541370/32deca0e-85da-4a71-bb8f-fbf7c79697d7)
In the figure, WSS means the FO, WMLES means ODE-type Wall model.

**Comment by timofeymukha** [comment]
Thanks for the graphs. I guess large deviations are definitely not expected, but one needs to consider the details, so it is good that you brought this up.
